### ISSUE TITLE
SignaturePad doesnt work/shows in TI-Client

### ISSUE THREAD

**Issue by r4inX** [Servoy/svySignature#2]
I updated my solution from NG to TI and now the Sign-Pad doesnt work. It neither shows up in the form-designer nor in the solution. (You can still edit the properties in the outline-tab).
Maybe it needs to be updated to TI?

**Comment by tuanway** [comment]
Hi @r4inX .. Titanium support will be available in the next official release (v.2202.06)

Should be available now! (please review and let us know if there are any issues)

thanks!
